# THIS DICTIONARY HAS ONLY ACRONYMS or SPECIAL JARGONS.
# Therefore commands like "history", "touch", or "top" will not be included here.

wdim:
  what does it mean
man:
  manual pages
mkdir:
  make directory
pwd:
  print working directory
cat:
  catenate
cd:
  change directory
chmod:
  change mode
vim:
  vi improved
ls:
  list segments
tar: 
  tape archives 
curl: 
  client for urls
grep:
  global regular expressions print
sed:
  stream editor
ln:
  link
bash:
  bourne-again shell
